<?php if($reviews = $this->getReviews()): ?>
    <div class="block block-reviews-store">
        <div class="block-title">
            <strong><span><?php echo $this->__('Customer reviews') ?></span></strong>
        </div>
        <div class="block-content">
            <?php foreach($reviews as $review): ?>
                <div class="replyBlock">
                    <div class="headReply">
                        <span><?php echo $this->__('%s wrote:', $review->getName()) ?></span>
                    </div>
                    <p><?php echo $review->getShopRew() ?></p>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>

